final_l2_error: 1.0280935764312744
final_ll: 618.229736328125
best_ll: 629.72265625
best_ll_epoch: 71
epochs: 200
data_truth_path: gLV/data/glv_ahidden0p00_truth.npz
data_obs_path: gLV/data/glv_ahidden0p00_obs.npz
init_theta_scale: 0.5
lr: 0.01
process_std: 0.0
N_ens: 50
chunk_length: 10
